# Generated by Django 4.2.3 on 2023-07-29 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=250)),
                ('fees', models.IntegerField(max_length=250)),
                ('duration', models.IntegerField(max_length=250)),
                ('comment', models.CharField(max_length=1000)),
            ],
        ),
    ]
