# Generated by Django 4.2.3 on 2023-07-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=250)),
                ('fees', models.CharField(max_length=250)),
                ('duration', models.CharField(max_length=250)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
    ]
