# Generated by Django 4.2.3 on 2023-08-01 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_saddress_addstudents_stcollege_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addstudents',
            old_name='stcollege',
            new_name='scollege',
        ),
        migrations.RenameField(
            model_name='addstudents',
            old_name='stcourse',
            new_name='scourse',
        ),
        migrations.RenameField(
            model_name='addstudents',
            old_name='stdegree',
            new_name='sdegree',
        ),
        migrations.RenameField(
            model_name='addstudents',
            old_name='stemail',
            new_name='semail',
        ),
        migrations.RenameField(
            model_name='addstudents',
            old_name='stmobile',
            new_name='smobile',
        ),
        migrations.RenameField(
            model_name='addstudents',
            old_name='stname',
            new_name='sname',
        ),
    ]
