# Generated by Django 4.2.3 on 2023-08-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_addstudents_paid_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addstudents',
            name='due_amount',
        ),
        migrations.AddField(
            model_name='addstudents',
            name='sdueAmount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addstudents',
            name='spaidAmount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addstudents',
            name='stotalAmount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
