# Generated by Django 4.2.3 on 2023-08-17 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_addstudents_due_amount_addstudents_sdueamount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddTeachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=250)),
                ('temp_id', models.CharField(max_length=250)),
                ('temail', models.EmailField(max_length=250)),
                ('tpsw', models.CharField(max_length=255)),
                ('tmobile', models.IntegerField()),
                ('tjoindate', models.IntegerField()),
                ('teducation', models.CharField(max_length=250)),
                ('tcourses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.addcourses')),
            ],
        ),
    ]
