# Generated by Django 4.2.3 on 2023-08-17 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_addteachers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addteachers',
            old_name='tcourses',
            new_name='tcourse',
        ),
    ]
