# Generated by Django 4.2.3 on 2023-08-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_tcourses_addteachers_tcourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addteachers',
            name='tjoindate',
            field=models.CharField(max_length=250),
        ),
    ]
