# Generated by Django 4.2.3 on 2023-08-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_addteachers_tjoindate'),
    ]

    operations = [
        migrations.AddField(
            model_name='addteachers',
            name='tgender',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
